---
# # Variables
# owner_name: "{{site.github.owner_name}}"
# repository_name: "{{site.github.repository_name}}"

# Site settings
title: "${{env.GITHUB_REPOSITORY_OWNER}}'s Personal Website"
description: "A personal website for ${{env.GITHUB_REPOSITORY_OWNER}}"
url: "https://${{env.GITHUB_REPOSITORY_OWNER}}.github.io"
baseurl: "/${{env.GITHUB_REPOSITORY}}"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub Pages settings
github:
  username: "${{env.GITHUB_REPOSITORY_OWNER}}"
  repository: "${{env.GITHUB_REPOSITORY}}"

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
